name: Commend on check
on:
  workflow_run:
    workflows: [Thank Contributor]
    types:
      - completed


jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event}}"
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Check has finished!
          comment_includes: "Check has finished"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

