name: Commend on check
on: 
  check_run:
    types: [completed]

jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Check has finished!
          comment_includes: "Check has finished"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
