name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    steps:
      - name: Get admin users
        shell: bash -l {0}
        run: |
          mkdir ~/.ssh >/dev/null 2>&1 && chmod 700 ~/.ssh
          curl  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/collaborators | \
            jq -r '.[] | select(.permissions.admin == true) | .login' > ~/.ssh/admins
          cat ~/.ssh/admins | xargs -I {} curl -s https://api.github.com/users/{}/keys | \
            jq '.[].key' --raw-output > ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys

      - name: Configure tmate
        shell: bash -l {0}
        run: |
          echo 'set tmate-authorized-keys "~/.ssh/authorized_keys"' > ~/.tmate.conf

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 2
