name: ollama
on: push
jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ollama
        uses: ai-action/setup-ollama@v1

      - name: Run LLM
        run: ollama run llama3.2 'Explain the basics of machine learning.'
