name: Thank Contributor!
on: pull_request_target

jobs:
  thank_contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Thank you for your contribution. We aim to review it within 48 hours!
          comment_includes: "Thank you"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
