name: Test neutral return
on: push

jobs:
  bashretry:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check something but exit neutrally
        run: |
          echo "Nothing to do, exiting with neutral code"
          exit 78
