name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Say Hello World
      uses: ajilraju/helloworld-actions@v1.3
