name: Test bash retry
on: push

jobs:
  bashretry:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Retry
        run: |
          until false; do
            false && break
            echo "Retrying..."
            sleep 1
          done
